# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dloglik_likelihood_gradient <- function(knot, facility, delta, z, b_spline, theta, N) {
    .Call(`_SurvTime_dloglik_likelihood_gradient`, knot, facility, delta, z, b_spline, theta, N)
}

ddloglik_gradient <- function(knot, facility, z, delta, b_spline, theta, number_facility = 1L) {
    .Call(`_SurvTime_ddloglik_gradient`, knot, facility, z, delta, b_spline, theta, number_facility)
}

GDboost_gradient <- function(knot, rate, facility, delta, z, b_spline, theta) {
    .Call(`_SurvTime_GDboost_gradient`, knot, rate, facility, delta, z, b_spline, theta)
}

dloglik_likelihood_stratify <- function(knot, facility, delta, z, b_spline, theta, N) {
    .Call(`_SurvTime_dloglik_likelihood_stratify`, knot, facility, delta, z, b_spline, theta, N)
}

ddloglik <- function(knot, facility, delta, z, b_spline, theta, number_facility = 1L) {
    .Call(`_SurvTime_ddloglik`, knot, facility, delta, z, b_spline, theta, number_facility)
}

